### ISSUE TITLE
Request for a new feature: check recursive theory

### ISSUE THREAD

**Issue by MatteoMagnini** [tuProlog/2p-kt#430]
It would be great to have functionalities to check if a theory contains recursion. In other words what I need is a checker for logic subsets of Prolog (e.g., Datalog), in particular the checker should tell when the following conditions are true:

- a theory contains recursive predicates or structures.
  Positive example:
  `friend(P1, P2) :- 
        friendOf(P1, P2).
    friend(P1, P2) :- 
        friendOf(P1, P3),
        friend(P3, P2).`
- a theory contains indirect recursive predicates.
   Positive example:
  `p1(X, Y, Z) :-
          p2(Y, X, Z).
    p2(X, Y, Z) :- 
          p1(Y, X, Z).`
- a theory contains potentially unlimited lists (or any structures in general).
   Positive example:
  `minimum([H | T], X) :-
         minimum2(T, H, X).
    minimum2([ ], X, X).
    minimum2([H | T], Y, X) :-
          H =< Y,
          minimum2(T, H, X).
    minimum2([H1 | T], Y, X) :-
          H > Y,
          minimum2([T, Y, X).`
   However, I can have a theory with lists (or any structures in general) whose length is known a priori.
   Negative example:
   `minimum[X1, X2, X3], X) :-
         X1 =< X2,
         X1 =< X3,
         X is X1.
      minimum([X1, X2, X3], X) :-
         X2 =< X1,
         X2 =< X3,
         X is X2.
      minimum([X1, X2, X3], X) :-
         X3 =< X1,
         X3 =< X2,
         X is X3.`

**Comment by gciatto** [comment]
This feature is now part of the `:datalog` module.

Examples here:
- https://github.com/tuProlog/2p-kt/blob/132f7c0566333bc36013162819b5689aa5bb678f/datalog/src/commonTest/kotlin/it/unibo/tuprolog/datalog/TestDatalog.kt#L71
- https://github.com/tuProlog/2p-kt/blob/132f7c0566333bc36013162819b5689aa5bb678f/datalog/src/commonTest/kotlin/it/unibo/tuprolog/datalog/TestDatalog.kt#L87

@MatteoMagnini can you tell whether that's what you were expecting?
