### ISSUE TITLE
Support for user defined predicate true/1

### ISSUE THREAD

**Issue by hurufu** [tuProlog/2p-kt#5]
Hello,

First of all, thanks for a great portable Prolog implementation.

I'm experimenting with reasoning in [GDL](https://en.wikipedia.org/wiki/Game_Description_Language). It's a subset of Prolog that is used to specify games for an AI to play.

The issue is that it requires the ability to assert some statements about a game using `true/1` predicate, but it seems like even a  simple example can't be handled by tuProlog.

If I create a file `example.pdb` with the following contents:
```
true(_).
```

I'm getting the output:
```
# 2P-Kt version 0.18.1
# Error while parsing theory file: example.pdb
#     Message: mismatched input '(' expecting {SIGN, ',', '|', FULL_STOP, OPERATOR}
#     Line   : 1
#     Column : 5
#     Clause : 0

# Successfully loaded library `prolog.io`
# Successfully loaded library `prolog.lang`

?- 
```

I'm using `2p-repl-0.18.1-redist.jar`.

Can this issue be somehow solved?

**Comment by gciatto-unibo** [comment]
OMG. That was a definitely dumb mistake of mine.

This is a simple parsing issue and it should be quite trivial to fix.
I'll do it within this week.

In the meanwhile, you should be able to work around this issue by writing:
```

**Comment by hurufu** [comment]
Yes, `'true'(_).` seems working just find.

**Comment by gciatto-unibo** [comment]
Ok I should have fixed it.
https://gitlab.com/pika-lab/tuprolog/2p-in-kotlin/-/merge_requests/123

I'll release version `0.18.2` soon
